version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: link-shorter-db
    environment:
      POSTGRES_DB: linksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: link-shorter-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: